#pragma once

// Lines are pre-wrapped for the 320 px external display. Keep each line short.
static const char* const CARDC_GUIDE_TEXT[] = {
  "# CardC - C LAB Reference", "",
  "CardC is a safe local C-style language.",
  "It interprets code; it does not run native code.", "",
  "# Editor controls",
  "Type text | ENTER: split or add a line",
  "DEL: erase before cursor | hold: repeat",
  "TAB: navigation mode",
  ";/. line up/down | ,/ char left/right",
  "CTRL+ENTER: run | CTRL+D: load demo",
  "CTRL+L: clear editor | CTRL+G: this guide", "",
  "# Basic rules",
  "End statements with ; | // starts a comment",
  "Numbers are signed integers; no decimals.",
  "Operators: +  -  *  /  %",
  "* / % run before + -; no parentheses.",
  "= assigns; + also joins text.", "",
  "# int variables",
  "int x;              // creates x as 0",
  "int x = 7;          // creates x with a value",
  "x = x * 2 + 1;   x++;   x--;", "",
  "# Text, numbers and keyboard input",
  "String name = input(\"Your name?\");",
  "int age = inputint(\"Your age?\");",
  "String key = readkey(\"Press a key\");",
  "input() accepts text; inputint() accepts one whole number.",
  "readkey() waits for one printable key; ENTER confirms input().", "",
  "# Output",
  "print(x);  println(\"Hello \" + name);",
  "puts(\"text\");  printf(x);",
  "Each call adds a line; newest five are shown.",
  "clear() clears OUTPUT; help() prints a hint.", "",
  "# if and while (one statement body)",
  "if (x > 0) println(\"positive\");",
  "while (x < 3) x++;",
  "Comparisons: ==  !=  <  <=  >  >=",
  "while is capped at 32 repeats per run.", "",
  "# Functions",
  "void greet() { println(\"Hi!\"); }",
  "greet();",
  "Functions have no parameters or return values.",
  "void setup() and void loop() each run once.", "",
  "# Read-only system values",
  "battery | uptime | free_heap_kb",
  "total_heap_kb | flash_mb",
  "device_name | theme_name | uptime_text", "",
  "# Wi-Fi values and scan",
  "wifi_scan() scans nearby networks locally.",
  "wifi_networks | wifi_connected",
  "wifi_rssi | wifi_ssid",
  "It never connects or asks for passwords.", "",
  "# Speaker beep (built-in)",
  "beep();              // 1000 Hz for 80 ms",
  "beep(880, 120);      // frequency Hz, duration ms",
  "Allowed: 40-8000 Hz and 1-2000 ms.",
  "Uses Settings > Volume; Volume 0% is silent.", "",
  "# Vibration motor (ready-made driver on G1)",
  "vibrate(80);          // motor ON for 80 ms, then OFF",
  "Allowed: 1-1000 ms. It is simple ON/OFF, not PWM.",
  "The motor module must be connected: G1 to IN, 3V3 to VCC,",
  "GND to GND, and the motor only to M+ and M-.", "",
  "# RGB status LED (built-in)",
  "led(r, g, b);         // each component is 0..255",
  "Example: led(255, 0, 128); // pink-purple",
  "This sets the built-in RGB LED until another state changes it.",
  "System states: red = backlight off; yellow = locked;",
  "green = unlocked. Your CardC colour is otherwise retained.", "",
  "# Keyboard action: ifkey()",
  "ifkey(\"a\")do(beep());",
  "Runs one CardC action only while that key is held.",
  "Use one printable key in quotes; action is one statement.",
  "Example: ifkey(\" \")do(beep(880,40));",
  "It checks the keyboard at that point in the current run.", "",
  "# Motion sensor: imuread()",
  "imuread(); // prints accelerometer and gyro values",
  "Uses the built-in Cardputer ADV IMU.", "",
  "# Bottom notification: toast()",
  "toast(\"Saved\");      // small message at screen bottom",
  "toast(\"Hi \" + name); // text can use String variables",
  "It appears briefly, then the current app redraws its covered area.",
  "Use it for a short status message, not a long log.", "",
  "# Program control",
  "wait(ms);             // pauses this program: 1..10000 ms",
  "halt(exitcode);       // ends this run and reports the code",
  "prgrestart();         // starts this CardC program again",
  "prgrestart() restarts only CardC, not the device.",
  "Restart is capped at 4 per Run to avoid endless loops.", "",
  "# Canvas: shapes and simple animation",
  "canvas_begin();       // opens the drawing view",
  "canvas_clear(0);      // colour index 0..8",
  "rect(x,y,w,h,c);      fill_rect(x,y,w,h,c);",
  "circle(x,y,r,c);      fill_circle(x,y,r,c);",
  "line(x1,y1,x2,y2,c);  pixel(x,y,c);",
  "canvas_pause(ms);     // 1..1000 ms between frames",
  "Colours: 0 black, 1 white, 2 cyan, 3 red,",
  "4 green, 5 blue, 6 yellow, 7 magenta, 8 orange.",
  "Canvas coordinates: x 0..319; drawing begins at y 19.",
  "Example: canvas_begin(); fill_circle(160,120,24,2);",
  "For animation, clear, draw the next frame, then pause.",
  "FN closes Canvas and returns to the C LAB editor.", "",
  "# Infrared sender (built-in)",
  "ir_nec(0, 16);  // address, command: 0..255",
  "Sends one standard NEC IR frame via the built-in emitter.",
  "IR sends only when this command is run.",
  "Cardputer ADV has no built-in IR receiver, so it cannot",
  "confirm that the target device received the command.", "",
  "# QR output",
  "qrcode(\"hello\");  qrcode(\"Hi \" + name);",
  "qrcode(input(\"URL:\")); // accepts https:// addresses",
  "QR text: printable ASCII, 1-106 characters.",
  "FN closes QR and returns to C LAB.", "",
  "# Limits",
  "32 code lines | 48 chars per line | 12 int vars",
  "8 String vars | 8 void functions | 4 inputs", "",
  "# Not available by design",
  "No arrays, pointers, files, GPIO or native code.",
  "No microphone access from CardC (use the MIC app instead).",
  "No Wi-Fi connections, credentials or system access.",
  "Errors stop the run and appear as ERR: in OUTPUT."
};

constexpr int CARDC_GUIDE_LINES = sizeof(CARDC_GUIDE_TEXT) / sizeof(CARDC_GUIDE_TEXT[0]);
